models/room.py
class Room:

    def __init__(self, id, name, description = None, members = [], public = True, admin = []):
        self.__id = id
        self.__name = name
        self.__description = description
        self.__members = members
        self.__public = public
        self.__admin = admin

    def get_name(self):
        return self.__name
    
    def set_name(self, name):
        self.__name = name

    def get_id(self):
        return self.__id

    def get_description(self):
        return self.__description

    def set_description(self, description):
        self.__description = description
    
    def get_members(self):
        return self.__members

    def add_member(self, member_id: str):
        self.__members.append()
    
    def get_public(self):
        return self.__public
    
    def set_public(self, public: bool):
        return self.__public
        
    def get_admin(self):
        return self.__admin

    def set_admin(self, admin: str):
        self.__admin.append(admin)

blueprints/rooms.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from flask_login import login_user, logout_user, login_required, current_user, LoginManager
from models.room import Room
import re
from services.database import Database
from models.user import User

rooms = Blueprint('rooms', __name__, url_prefix='/rooms',
                 static_folder="static", template_folder="/rooms/")
database = Database()


@login_required
@rooms.route("/")
def root():
    rooms = database.get_room_by_user(current_user.get_id())
    print(rooms)
    if rooms is not None:
        return render_template("rooms/rooms.html", rooms = rooms)
    return render_template("rooms/rooms.html")

@login_required
@rooms.route("/create", methods=["GET", "POST"])
def create():
    if request.method == "POST":
        name = request.form['name']
        description = request.form['description']
        public = request.form['public']

        if database.create_room(name, description, public, current_user.get_id()):
            flash("Room created, go have fun!",
                  category="success")
        return redirect(url_for(root))

    elif request.method == "GET":
        return render_template("rooms/create.html")


@login_required
@rooms.route("/connect", methods=["GET", "POST"])
def connect():
    room_id = request.args.get("id")
    # TODO get single Room that has ID
    result = database.get_room_by_id(room_id)

    if result:
        room = Room(result["_id"], result["name"], result["description"], result["members"], result["public"], result["admin"])
        print(room)
        current_user.set_current_room(room)

        if current_user.get_id() not in result["members"]:
            database.add_member_to_room(current_user.get_id(), result["_id"])

        return render_template("rooms/room.html", room = room)

    flash("That room does not exist!", "error")
    return redirect(url_for("rooms.root"))

@login_required
@rooms.route("/discover", methods=["GET"])
def discover():
    if request.method == "POST":
        # TODO Post redirect to connect with id param
        room_id = request.args.get("id")
        return redirect(url_for("rooms.connect", id = room_id))


    elif request.method == "GET":
        # TODO Fetch public rooms from database
        public_rooms = database.get_public_rooms()
        print(public_rooms)
        return render_template("rooms/rooms.html", rooms = public_rooms, discover = True)

# TODO Check if this is good
@rooms.route("/invite", methods=["GET", "POST"])
def invite():
    room_id = request.args.get("id")
    print(room_id)
    # TODO get single Room that has ID
    result = database.get_room_by_id(room_id)

    if result:
        print("ROOM IS FOUND")
        if current_user.get_id() in result["admin"]:
            return render_template("rooms/invite.html", admin = True)

        flash("You're now a member!", "success")
        return redirect(url_for(rooms.root))

    flash("That room does not exist!", "error")
    return redirect(url_for("rooms.root"))

templates/rooms/create.html
{% extends '/base.html' %}
{% block content%}
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column ">
          <form action="" class="box" id="formbox" method="post">
            <div class="field">
              <label for="" class="label" id="subtitle">Name</label>
              <div class="control">
                <input type="text" placeholder="Choose a name for the room" name="name" class="input" required>
              </div>
            </div>
            <div class="field">
                <label for="" class="label" id="subtitle">Description</label>
                <div class="control">
                  <input type="text" placeholder="Create a description" name="description" class="input" required>
                </div>
            </div>
            <div class="field">
              <label for="" class="checkbox">
                Publicity
              </label>
              <div class="control">
                <label class="radio">
                  <input type="radio" name="public">
                  Public
                </label>
                <label class="radio">
                  <input type="radio" name="public">
                  Private
                </label>
              </div>
            </div>
            <div class="field">
              <button class="button is-primary">
                Create
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock%}

templates/rooms/invite.html
{% extends 'base.html' %}
{% block content%}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        INVITE HUB
      </p>
    </div>
  </div>
  </div>
</section>

{% endblock%}

templates/rooms/room.html
{% extends 'base.html' %}
{% block head %}
<script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
    var socket = io();

console.log('check 1', socket.connected);
socket.on('connect', function() {
  console.log('check 2', socket.connected);
});
  socket.on('connect', function () {
      socket.emit('join_room', {
          username: "{{ current_user.get_id() }}",
          room: "{{ room.get_id() }}"
      });

      let message_input = document.getElementById('message_input');

      console.log("Joined room fr fr")

      document.getElementById('message_input_form').onsubmit = function (e) {
          e.preventDefault();
          let message = message_input.value.trim();
          if (message.length) {
              socket.emit('send_message', {
                  username: "{{ current_user.get_id() }}",
                  room: "{{ room.get_id() }}",
                  message: message
              })
          }
          message_input.value = '';
          message_input.focus();
      }
  });

  window.onbeforeunload = function () {
      socket.emit('leave_room', {
          username: "{{ username }}",
          room: "{{ room }}"
      })
  };

  socket.on('receive_message', function (data) {
      console.log(data);
      const newNode = document.createElement('div');
      newNode.innerHTML = ` <div class="card ">
                            <div id="messages">
                            <div class="card-content ">
                              <div class="media">
                                <div class="media-content">
                                    <p class="title is-4 " id="title">${data.username}</p>
                                    <p class="subtitle is-5 " id ="subtitle">${data.message}</p>
                                </div>
                              </div>
                            </div>`;
      document.getElementById('messages').appendChild(newNode);
  });

  socket.on('join_room_announcement', function (data) {
      console.log(data);
      if (data.username !== "{{ username }}") {
          const newNode = document.createElement('div');
          newNode.innerHTML = `<div class="card-content">
                            <nav class="level">
                              <p class="level-item has-text-centered">
                                <a class="level-item is-info">${data.username} just joined</a>
                              </p>
                              
                            </nav>
                          </div>`;
          console.log(newNode.innerHTML)
          document.getElementById('messages').appendChild(newNode);
                        }
      
  });

  socket.on('leave_room_announcement', function (data) {
      console.log(data);
      const newNode = document.createElement('div');
      newNode.innerHTML = `<b>${data.username}</b> has left the room`;
      document.getElementById('messages').appendChild(newNode);
  });
</script>
{% endblock head %}
{% block content%}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        ROOMS
      </p>
    </div>
  </div>
  </div>

</section>

<section class="section">
  <h1 class="title">{{room.get_name()}}</h1>
  <h2 class="subtitle">
    {{room.get_description()}}
  </h2>
  <div id ="invite"></div>

  {% if current_user.get_id() in room.get_admin() %}
  <!-------------------- TODO SORT THIS B------------------->

<nav class="level">
  <div class="level-item has-text-centered">
    <div>
      <button class="button">Settings</button>
    </div>
  </div>
  <div class="level-item has-text-centered">
    <div>
      <a href={{url_for("rooms.invite", id= room.get_id())}}>
      <button class="button">Get invite link</button>
    </a>
    </div>
  </div>

</nav>
  {% endif %}

</section>

<section class="section">

  <!--BODY FOR MESSAGE--->
 
  <div class="card ">
    <div id="messages">
    <div class="card-content ">
  </div>
  </div>

  <!---Messages id ends here-->
  <form id="message_input_form">
    <div class="field has-addons">
      <div class="control is-expanded">
        <input type="text" class="input"  id="message_input"  placeholder="Type your message">
      </div>
      <div class="control">
        <button class="button is-info">Send</button>
      </div>
    </div>
  </form>
</section>

{% endblock%}

templates/rooms/rooms.html
{% extends 'base.html' %}
{% block content%}
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        {% if discover%}
        DISCOVER ROOMS
        {% else %}
        ROOMS
        {% endif %}
      </p>
    </div>
  </div>
  </div>
</section>

<section class="section">
  <h1 class="title">Create a room</h1>
  <h2 class="subtitle">
    Create your own community!
  </h2>
  <a href="create">
    <button class="button">Create community</button>
  </a>

</section>

<section class="section">
  {% if discover%}
  <h1 class="title">Public rooms</h1>
  <h2 class="subtitle">
    Click a room to connect!
  </h2>
  {% else %}
  <h1 class="title">My rooms</h1>
  <h2 class="subtitle">
    Click a room to connect!
  </h2>
  {% endif %}


  {% if not rooms %}
  <h2 class="subtitle">
    No rooms available!
  </h2>
  {% endif %}

  {% for item in rooms %}
  <div class="card">
    <div class="card-content">
      <div class="media">
        <div class="media-content">
            <p class="title is-4" id="title">{{item.get("name")}}</p>
            <p class="subtitle is-5" id ="subtitle">{{item.get("description")}} </p>
            <p class="subtitle is-6" id ="subtitle">Room is 
              {% if item.get("public") == "on"%}
              public
              {% else %}
              private
              {% endif %}
            </p>
        </div>
        <div class="media-right">
          <a href={{url_for("rooms.connect", id=item.get("id"))}}>
          <button class="button">Connect</button>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor%}

  


</section>
{% endblock%}